-- Árvore de assuntos da vertical Medicina (área › matéria › tópico).
-- Espinha dorsal: matriz de referência do ENEM, com os tópicos já usados nos
-- simulados Med dobrados dentro dela. APLICADA EM PRODUÇÃO via REST em 08/09/2026;
-- este arquivo existe para reproduzir a árvore num ambiente novo.
-- Reverter:  delete from arvore_materias where vertical = 'Medicina';
--            delete from arvore_areas    where vertical = 'Medicina';

insert into arvore_areas (nome, vertical, ordem) values
  ('Linguagens, Códigos e suas Tecnologias', 'Medicina', 0),
  ('Matemática e suas Tecnologias', 'Medicina', 1),
  ('Ciências da Natureza e suas Tecnologias', 'Medicina', 2),
  ('Ciências Humanas e suas Tecnologias', 'Medicina', 3);

insert into arvore_materias (nome, vertical, ordem, area_id) values
  ('Língua Portuguesa', 'Medicina', 0, (select id from arvore_areas where nome = 'Linguagens, Códigos e suas Tecnologias' and vertical = 'Medicina')),
  ('Literatura', 'Medicina', 1, (select id from arvore_areas where nome = 'Linguagens, Códigos e suas Tecnologias' and vertical = 'Medicina')),
  ('Redação', 'Medicina', 2, (select id from arvore_areas where nome = 'Linguagens, Códigos e suas Tecnologias' and vertical = 'Medicina')),
  ('Inglês', 'Medicina', 3, (select id from arvore_areas where nome = 'Linguagens, Códigos e suas Tecnologias' and vertical = 'Medicina')),
  ('Espanhol', 'Medicina', 4, (select id from arvore_areas where nome = 'Linguagens, Códigos e suas Tecnologias' and vertical = 'Medicina')),
  ('Artes', 'Medicina', 5, (select id from arvore_areas where nome = 'Linguagens, Códigos e suas Tecnologias' and vertical = 'Medicina')),
  ('Matemática', 'Medicina', 6, (select id from arvore_areas where nome = 'Matemática e suas Tecnologias' and vertical = 'Medicina')),
  ('Física', 'Medicina', 7, (select id from arvore_areas where nome = 'Ciências da Natureza e suas Tecnologias' and vertical = 'Medicina')),
  ('Química', 'Medicina', 8, (select id from arvore_areas where nome = 'Ciências da Natureza e suas Tecnologias' and vertical = 'Medicina')),
  ('Biologia', 'Medicina', 9, (select id from arvore_areas where nome = 'Ciências da Natureza e suas Tecnologias' and vertical = 'Medicina')),
  ('História', 'Medicina', 10, (select id from arvore_areas where nome = 'Ciências Humanas e suas Tecnologias' and vertical = 'Medicina')),
  ('Geografia', 'Medicina', 11, (select id from arvore_areas where nome = 'Ciências Humanas e suas Tecnologias' and vertical = 'Medicina')),
  ('Filosofia', 'Medicina', 12, (select id from arvore_areas where nome = 'Ciências Humanas e suas Tecnologias' and vertical = 'Medicina')),
  ('Sociologia', 'Medicina', 13, (select id from arvore_areas where nome = 'Ciências Humanas e suas Tecnologias' and vertical = 'Medicina'));

insert into arvore_topicos (nome, materia_id, ordem, vertical) values
  ('Aritmética e problemas', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 0, 'Medicina'),
  ('Razão, proporção e porcentagem', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 1, 'Medicina'),
  ('Grandezas proporcionais e regra de três', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 2, 'Medicina'),
  ('Conjuntos numéricos', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 3, 'Medicina'),
  ('Equações e inequações', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 4, 'Medicina'),
  ('Sistemas lineares', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 5, 'Medicina'),
  ('Sequências e progressões', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 6, 'Medicina'),
  ('Funções: conceito e gráficos', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 7, 'Medicina'),
  ('Função afim', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 8, 'Medicina'),
  ('Função quadrática', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 9, 'Medicina'),
  ('Função exponencial e logarítmica', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 10, 'Medicina'),
  ('Trigonometria', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 11, 'Medicina'),
  ('Geometria plana', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 12, 'Medicina'),
  ('Geometria espacial', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 13, 'Medicina'),
  ('Geometria analítica', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 14, 'Medicina'),
  ('Análise combinatória', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 15, 'Medicina'),
  ('Probabilidade', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 16, 'Medicina'),
  ('Estatística e interpretação de dados', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 17, 'Medicina'),
  ('Matemática financeira', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 18, 'Medicina'),
  ('Matrizes e determinantes', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 19, 'Medicina'),
  ('Grandezas e medidas', (select id from arvore_materias where nome = 'Matemática' and vertical = 'Medicina'), 20, 'Medicina'),
  ('Introdução: grandezas e unidades', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 0, 'Medicina'),
  ('Cinemática', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 1, 'Medicina'),
  ('Dinâmica: leis de Newton', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 2, 'Medicina'),
  ('Estática e equilíbrio', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 3, 'Medicina'),
  ('Trabalho, energia e potência', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 4, 'Medicina'),
  ('Impulso e quantidade de movimento', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 5, 'Medicina'),
  ('Gravitação universal', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 6, 'Medicina'),
  ('Hidrostática', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 7, 'Medicina'),
  ('Termometria e dilatação', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 8, 'Medicina'),
  ('Calorimetria e mudanças de estado', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 9, 'Medicina'),
  ('Termodinâmica e gases', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 10, 'Medicina'),
  ('Ondulatória e acústica', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 11, 'Medicina'),
  ('Óptica geométrica', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 12, 'Medicina'),
  ('Eletrostática', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 13, 'Medicina'),
  ('Eletrodinâmica: circuitos', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 14, 'Medicina'),
  ('Eletromagnetismo', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 15, 'Medicina'),
  ('Física moderna', (select id from arvore_materias where nome = 'Física' and vertical = 'Medicina'), 16, 'Medicina'),
  ('Propriedades da matéria e separação de misturas', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 0, 'Medicina'),
  ('Estrutura atômica', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 1, 'Medicina'),
  ('Tabela periódica', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 2, 'Medicina'),
  ('Ligações químicas', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 3, 'Medicina'),
  ('Geometria molecular e forças intermoleculares', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 4, 'Medicina'),
  ('Funções inorgânicas', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 5, 'Medicina'),
  ('Reações inorgânicas', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 6, 'Medicina'),
  ('Cálculos químicos e estequiometria', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 7, 'Medicina'),
  ('Gases', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 8, 'Medicina'),
  ('Soluções e concentração', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 9, 'Medicina'),
  ('Termoquímica', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 10, 'Medicina'),
  ('Cinética química', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 11, 'Medicina'),
  ('Equilíbrio químico', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 12, 'Medicina'),
  ('Equilíbrio iônico, pH e hidrólise', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 13, 'Medicina'),
  ('Eletroquímica', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 14, 'Medicina'),
  ('Radioatividade', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 15, 'Medicina'),
  ('Química orgânica: cadeias e nomenclatura', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 16, 'Medicina'),
  ('Funções orgânicas', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 17, 'Medicina'),
  ('Isomeria', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 18, 'Medicina'),
  ('Reações orgânicas', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 19, 'Medicina'),
  ('Bioquímica e polímeros', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 20, 'Medicina'),
  ('Química ambiental', (select id from arvore_materias where nome = 'Química' and vertical = 'Medicina'), 21, 'Medicina'),
  ('Bioquímica celular', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 0, 'Medicina'),
  ('Citologia: estrutura e organelas', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 1, 'Medicina'),
  ('Membrana e transportes', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 2, 'Medicina'),
  ('Metabolismo energético: respiração e fotossíntese', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 3, 'Medicina'),
  ('Divisão celular', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 4, 'Medicina'),
  ('Histologia', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 5, 'Medicina'),
  ('Fisiologia humana: sistema digestório', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 6, 'Medicina'),
  ('Fisiologia humana: circulatório e respiratório', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 7, 'Medicina'),
  ('Fisiologia humana: excretor e endócrino', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 8, 'Medicina'),
  ('Fisiologia humana: nervoso e sensorial', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 9, 'Medicina'),
  ('Reprodução e embriologia', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 10, 'Medicina'),
  ('Genética mendeliana', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 11, 'Medicina'),
  ('Genética molecular e biotecnologia', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 12, 'Medicina'),
  ('Evolução', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 13, 'Medicina'),
  ('Ecologia: ecossistemas e ciclos biogeoquímicos', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 14, 'Medicina'),
  ('Ecologia: populações e comunidades', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 15, 'Medicina'),
  ('Problemas ambientais', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 16, 'Medicina'),
  ('Botânica: morfologia e fisiologia vegetal', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 17, 'Medicina'),
  ('Zoologia e classificação dos seres vivos', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 18, 'Medicina'),
  ('Vírus, bactérias, protozoários e fungos', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 19, 'Medicina'),
  ('Saúde pública, parasitoses e imunologia', (select id from arvore_materias where nome = 'Biologia' and vertical = 'Medicina'), 20, 'Medicina'),
  ('Introdução à História e historiografia', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 0, 'Medicina'),
  ('Antiguidade: Oriente, Grécia e Roma', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 1, 'Medicina'),
  ('Idade Média', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 2, 'Medicina'),
  ('Idade Moderna: Renascimento, Reformas e Absolutismo', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 3, 'Medicina'),
  ('Grandes Navegações e expansão marítima', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 4, 'Medicina'),
  ('Brasil Colônia', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 5, 'Medicina'),
  ('Iluminismo e revoluções burguesas', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 6, 'Medicina'),
  ('Independências na América e período joanino', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 7, 'Medicina'),
  ('Brasil Império', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 8, 'Medicina'),
  ('Revolução Industrial e movimento operário', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 9, 'Medicina'),
  ('Imperialismo e neocolonialismo', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 10, 'Medicina'),
  ('Primeira República', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 11, 'Medicina'),
  ('Primeira Guerra e entreguerras', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 12, 'Medicina'),
  ('Era Vargas', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 13, 'Medicina'),
  ('Segunda Guerra Mundial', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 14, 'Medicina'),
  ('Guerra Fria', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 15, 'Medicina'),
  ('Ditadura militar no Brasil', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 16, 'Medicina'),
  ('Brasil republicano contemporâneo', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 17, 'Medicina'),
  ('História da África e relações raciais', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 18, 'Medicina'),
  ('América Latina contemporânea', (select id from arvore_materias where nome = 'História' and vertical = 'Medicina'), 19, 'Medicina'),
  ('Cartografia e orientação', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 0, 'Medicina'),
  ('Geologia e relevo', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 1, 'Medicina'),
  ('Clima e tempo', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 2, 'Medicina'),
  ('Hidrografia', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 3, 'Medicina'),
  ('Domínios morfoclimáticos e biomas', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 4, 'Medicina'),
  ('Questões ambientais e sustentabilidade', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 5, 'Medicina'),
  ('População e demografia', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 6, 'Medicina'),
  ('Migrações', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 7, 'Medicina'),
  ('Urbanização e geografia urbana', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 8, 'Medicina'),
  ('Espaço agrário e questão agrária', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 9, 'Medicina'),
  ('Industrialização', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 10, 'Medicina'),
  ('Fontes de energia', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 11, 'Medicina'),
  ('Geografia econômica e comércio', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 12, 'Medicina'),
  ('Globalização', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 13, 'Medicina'),
  ('Geopolítica e conflitos', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 14, 'Medicina'),
  ('Blocos econômicos', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 15, 'Medicina'),
  ('Regionalização do Brasil', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 16, 'Medicina'),
  ('Transportes e redes', (select id from arvore_materias where nome = 'Geografia' and vertical = 'Medicina'), 17, 'Medicina'),
  ('Introdução à Filosofia e o mito', (select id from arvore_materias where nome = 'Filosofia' and vertical = 'Medicina'), 0, 'Medicina'),
  ('Filosofia grega: pré-socráticos', (select id from arvore_materias where nome = 'Filosofia' and vertical = 'Medicina'), 1, 'Medicina'),
  ('Sócrates, Platão e Aristóteles', (select id from arvore_materias where nome = 'Filosofia' and vertical = 'Medicina'), 2, 'Medicina'),
  ('Filosofia medieval', (select id from arvore_materias where nome = 'Filosofia' and vertical = 'Medicina'), 3, 'Medicina'),
  ('Filosofia moderna: racionalismo e empirismo', (select id from arvore_materias where nome = 'Filosofia' and vertical = 'Medicina'), 4, 'Medicina'),
  ('Teoria do conhecimento', (select id from arvore_materias where nome = 'Filosofia' and vertical = 'Medicina'), 5, 'Medicina'),
  ('Ética e moral', (select id from arvore_materias where nome = 'Filosofia' and vertical = 'Medicina'), 6, 'Medicina'),
  ('Filosofia política', (select id from arvore_materias where nome = 'Filosofia' and vertical = 'Medicina'), 7, 'Medicina'),
  ('Estética', (select id from arvore_materias where nome = 'Filosofia' and vertical = 'Medicina'), 8, 'Medicina'),
  ('Lógica e argumentação', (select id from arvore_materias where nome = 'Filosofia' and vertical = 'Medicina'), 9, 'Medicina'),
  ('Filosofia contemporânea', (select id from arvore_materias where nome = 'Filosofia' and vertical = 'Medicina'), 10, 'Medicina'),
  ('Teoria crítica e Escola de Frankfurt', (select id from arvore_materias where nome = 'Filosofia' and vertical = 'Medicina'), 11, 'Medicina'),
  ('Existencialismo e fenomenologia', (select id from arvore_materias where nome = 'Filosofia' and vertical = 'Medicina'), 12, 'Medicina'),
  ('Introdução à Sociologia', (select id from arvore_materias where nome = 'Sociologia' and vertical = 'Medicina'), 0, 'Medicina'),
  ('Sociologia clássica: Durkheim, Weber e Marx', (select id from arvore_materias where nome = 'Sociologia' and vertical = 'Medicina'), 1, 'Medicina'),
  ('Cultura e identidade', (select id from arvore_materias where nome = 'Sociologia' and vertical = 'Medicina'), 2, 'Medicina'),
  ('Socialização e instituições sociais', (select id from arvore_materias where nome = 'Sociologia' and vertical = 'Medicina'), 3, 'Medicina'),
  ('Trabalho e sociedade', (select id from arvore_materias where nome = 'Sociologia' and vertical = 'Medicina'), 4, 'Medicina'),
  ('Estratificação e desigualdade social', (select id from arvore_materias where nome = 'Sociologia' and vertical = 'Medicina'), 5, 'Medicina'),
  ('Movimentos sociais', (select id from arvore_materias where nome = 'Sociologia' and vertical = 'Medicina'), 6, 'Medicina'),
  ('Direitos humanos e cidadania', (select id from arvore_materias where nome = 'Sociologia' and vertical = 'Medicina'), 7, 'Medicina'),
  ('Política, Estado e poder', (select id from arvore_materias where nome = 'Sociologia' and vertical = 'Medicina'), 8, 'Medicina'),
  ('Democracia e participação', (select id from arvore_materias where nome = 'Sociologia' and vertical = 'Medicina'), 9, 'Medicina'),
  ('Questão racial e pós-abolição', (select id from arvore_materias where nome = 'Sociologia' and vertical = 'Medicina'), 10, 'Medicina'),
  ('Gênero e diversidade', (select id from arvore_materias where nome = 'Sociologia' and vertical = 'Medicina'), 11, 'Medicina'),
  ('Violência e conflitos sociais', (select id from arvore_materias where nome = 'Sociologia' and vertical = 'Medicina'), 12, 'Medicina'),
  ('Globalização e sociedade em rede', (select id from arvore_materias where nome = 'Sociologia' and vertical = 'Medicina'), 13, 'Medicina'),
  ('Interpretação e compreensão de texto', (select id from arvore_materias where nome = 'Língua Portuguesa' and vertical = 'Medicina'), 0, 'Medicina'),
  ('Gêneros textuais', (select id from arvore_materias where nome = 'Língua Portuguesa' and vertical = 'Medicina'), 1, 'Medicina'),
  ('Funções da linguagem', (select id from arvore_materias where nome = 'Língua Portuguesa' and vertical = 'Medicina'), 2, 'Medicina'),
  ('Variação linguística', (select id from arvore_materias where nome = 'Língua Portuguesa' and vertical = 'Medicina'), 3, 'Medicina'),
  ('Figuras de linguagem', (select id from arvore_materias where nome = 'Língua Portuguesa' and vertical = 'Medicina'), 4, 'Medicina'),
  ('Coesão e coerência', (select id from arvore_materias where nome = 'Língua Portuguesa' and vertical = 'Medicina'), 5, 'Medicina'),
  ('Semântica e léxico', (select id from arvore_materias where nome = 'Língua Portuguesa' and vertical = 'Medicina'), 6, 'Medicina'),
  ('Fonética e ortografia', (select id from arvore_materias where nome = 'Língua Portuguesa' and vertical = 'Medicina'), 7, 'Medicina'),
  ('Acentuação', (select id from arvore_materias where nome = 'Língua Portuguesa' and vertical = 'Medicina'), 8, 'Medicina'),
  ('Morfologia: classes de palavras', (select id from arvore_materias where nome = 'Língua Portuguesa' and vertical = 'Medicina'), 9, 'Medicina'),
  ('Sintaxe: termos da oração', (select id from arvore_materias where nome = 'Língua Portuguesa' and vertical = 'Medicina'), 10, 'Medicina'),
  ('Período composto', (select id from arvore_materias where nome = 'Língua Portuguesa' and vertical = 'Medicina'), 11, 'Medicina'),
  ('Concordância verbal e nominal', (select id from arvore_materias where nome = 'Língua Portuguesa' and vertical = 'Medicina'), 12, 'Medicina'),
  ('Regência e crase', (select id from arvore_materias where nome = 'Língua Portuguesa' and vertical = 'Medicina'), 13, 'Medicina'),
  ('Pontuação', (select id from arvore_materias where nome = 'Língua Portuguesa' and vertical = 'Medicina'), 14, 'Medicina'),
  ('Tecnologias da informação e comunicação', (select id from arvore_materias where nome = 'Língua Portuguesa' and vertical = 'Medicina'), 15, 'Medicina'),
  ('Teoria literária e gêneros', (select id from arvore_materias where nome = 'Literatura' and vertical = 'Medicina'), 0, 'Medicina'),
  ('Trovadorismo e Humanismo', (select id from arvore_materias where nome = 'Literatura' and vertical = 'Medicina'), 1, 'Medicina'),
  ('Classicismo e Quinhentismo', (select id from arvore_materias where nome = 'Literatura' and vertical = 'Medicina'), 2, 'Medicina'),
  ('Barroco', (select id from arvore_materias where nome = 'Literatura' and vertical = 'Medicina'), 3, 'Medicina'),
  ('Arcadismo', (select id from arvore_materias where nome = 'Literatura' and vertical = 'Medicina'), 4, 'Medicina'),
  ('Romantismo', (select id from arvore_materias where nome = 'Literatura' and vertical = 'Medicina'), 5, 'Medicina'),
  ('Realismo e Naturalismo', (select id from arvore_materias where nome = 'Literatura' and vertical = 'Medicina'), 6, 'Medicina'),
  ('Parnasianismo e Simbolismo', (select id from arvore_materias where nome = 'Literatura' and vertical = 'Medicina'), 7, 'Medicina'),
  ('Pré-Modernismo', (select id from arvore_materias where nome = 'Literatura' and vertical = 'Medicina'), 8, 'Medicina'),
  ('Modernismo: 1ª geração', (select id from arvore_materias where nome = 'Literatura' and vertical = 'Medicina'), 9, 'Medicina'),
  ('Modernismo: 2ª geração', (select id from arvore_materias where nome = 'Literatura' and vertical = 'Medicina'), 10, 'Medicina'),
  ('Modernismo: 3ª geração e 1945', (select id from arvore_materias where nome = 'Literatura' and vertical = 'Medicina'), 11, 'Medicina'),
  ('Literatura contemporânea', (select id from arvore_materias where nome = 'Literatura' and vertical = 'Medicina'), 12, 'Medicina'),
  ('Literatura portuguesa', (select id from arvore_materias where nome = 'Literatura' and vertical = 'Medicina'), 13, 'Medicina'),
  ('Literaturas africanas de língua portuguesa', (select id from arvore_materias where nome = 'Literatura' and vertical = 'Medicina'), 14, 'Medicina'),
  ('Estrutura dissertativo-argumentativa', (select id from arvore_materias where nome = 'Redação' and vertical = 'Medicina'), 0, 'Medicina'),
  ('C1 – Norma culta', (select id from arvore_materias where nome = 'Redação' and vertical = 'Medicina'), 1, 'Medicina'),
  ('C2 – Compreensão do tema e repertório', (select id from arvore_materias where nome = 'Redação' and vertical = 'Medicina'), 2, 'Medicina'),
  ('C3 – Projeto de texto e argumentação', (select id from arvore_materias where nome = 'Redação' and vertical = 'Medicina'), 3, 'Medicina'),
  ('C4 – Coesão e conectivos', (select id from arvore_materias where nome = 'Redação' and vertical = 'Medicina'), 4, 'Medicina'),
  ('C5 – Proposta de intervenção', (select id from arvore_materias where nome = 'Redação' and vertical = 'Medicina'), 5, 'Medicina'),
  ('Temas e atualidades', (select id from arvore_materias where nome = 'Redação' and vertical = 'Medicina'), 6, 'Medicina'),
  ('Modelos de outras bancas', (select id from arvore_materias where nome = 'Redação' and vertical = 'Medicina'), 7, 'Medicina'),
  ('Interpretação de texto', (select id from arvore_materias where nome = 'Inglês' and vertical = 'Medicina'), 0, 'Medicina'),
  ('Vocabulário e cognatos', (select id from arvore_materias where nome = 'Inglês' and vertical = 'Medicina'), 1, 'Medicina'),
  ('Tempos verbais', (select id from arvore_materias where nome = 'Inglês' and vertical = 'Medicina'), 2, 'Medicina'),
  ('Modais e condicionais', (select id from arvore_materias where nome = 'Inglês' and vertical = 'Medicina'), 3, 'Medicina'),
  ('Conectivos e referência textual', (select id from arvore_materias where nome = 'Inglês' and vertical = 'Medicina'), 4, 'Medicina'),
  ('Voz passiva e discurso indireto', (select id from arvore_materias where nome = 'Inglês' and vertical = 'Medicina'), 5, 'Medicina'),
  ('Gêneros e propósito comunicativo', (select id from arvore_materias where nome = 'Inglês' and vertical = 'Medicina'), 6, 'Medicina'),
  ('Interpretação de texto', (select id from arvore_materias where nome = 'Espanhol' and vertical = 'Medicina'), 0, 'Medicina'),
  ('Vocabulário e heterossemânticos', (select id from arvore_materias where nome = 'Espanhol' and vertical = 'Medicina'), 1, 'Medicina'),
  ('Tempos verbais', (select id from arvore_materias where nome = 'Espanhol' and vertical = 'Medicina'), 2, 'Medicina'),
  ('Modais e condicionais', (select id from arvore_materias where nome = 'Espanhol' and vertical = 'Medicina'), 3, 'Medicina'),
  ('Conectivos e referência textual', (select id from arvore_materias where nome = 'Espanhol' and vertical = 'Medicina'), 4, 'Medicina'),
  ('Voz passiva e discurso indireto', (select id from arvore_materias where nome = 'Espanhol' and vertical = 'Medicina'), 5, 'Medicina'),
  ('Gêneros e propósito comunicativo', (select id from arvore_materias where nome = 'Espanhol' and vertical = 'Medicina'), 6, 'Medicina'),
  ('Artes visuais', (select id from arvore_materias where nome = 'Artes' and vertical = 'Medicina'), 0, 'Medicina'),
  ('História da arte e movimentos', (select id from arvore_materias where nome = 'Artes' and vertical = 'Medicina'), 1, 'Medicina'),
  ('Arte brasileira', (select id from arvore_materias where nome = 'Artes' and vertical = 'Medicina'), 2, 'Medicina'),
  ('Arte indígena e afro-brasileira', (select id from arvore_materias where nome = 'Artes' and vertical = 'Medicina'), 3, 'Medicina'),
  ('Música', (select id from arvore_materias where nome = 'Artes' and vertical = 'Medicina'), 4, 'Medicina'),
  ('Teatro', (select id from arvore_materias where nome = 'Artes' and vertical = 'Medicina'), 5, 'Medicina'),
  ('Dança', (select id from arvore_materias where nome = 'Artes' and vertical = 'Medicina'), 6, 'Medicina'),
  ('Fotografia e audiovisual', (select id from arvore_materias where nome = 'Artes' and vertical = 'Medicina'), 7, 'Medicina'),
  ('Práticas corporais e Educação Física', (select id from arvore_materias where nome = 'Artes' and vertical = 'Medicina'), 8, 'Medicina');
